-- ============================================================
-- Copa 2026 AI — Tradução dos nomes das seleções para PT-BR
-- Atualiza diretamente a coluna name e short_name
-- Execute no SQL Editor do Supabase
-- ============================================================

UPDATE teams SET
    name = CASE name
        WHEN 'Mexico'              THEN 'México'
        WHEN 'United States'       THEN 'Estados Unidos'
        WHEN 'Canada'              THEN 'Canadá'
        WHEN 'Serbia'              THEN 'Sérvia'
        WHEN 'Panama'              THEN 'Panamá'
        WHEN 'Algeria'             THEN 'Argélia'
        WHEN 'Ecuador'             THEN 'Equador'
        WHEN 'Ivory Coast'         THEN 'Costa do Marfim'
        WHEN 'Peru'                THEN 'Peru'
        WHEN 'Germany'             THEN 'Alemanha'
        WHEN 'Japan'               THEN 'Japão'
        WHEN 'Nigeria'             THEN 'Nigéria'
        WHEN 'Colombia'            THEN 'Colômbia'
        WHEN 'Paraguay'            THEN 'Paraguai'
        WHEN 'France'              THEN 'França'
        WHEN 'England'             THEN 'Inglaterra'
        WHEN 'Austria'             THEN 'Áustria'
        WHEN 'Cameroon'            THEN 'Camarões'
        WHEN 'Saudi Arabia'        THEN 'Arábia Saudita'
        WHEN 'Spain'               THEN 'Espanha'
        WHEN 'Netherlands'         THEN 'Holanda'
        WHEN 'Australia'           THEN 'Austrália'
        WHEN 'South Africa'        THEN 'África do Sul'
        WHEN 'Slovenia'            THEN 'Eslovênia'
        WHEN 'Belgium'             THEN 'Bélgica'
        WHEN 'Croatia'             THEN 'Croácia'
        WHEN 'Indonesia'           THEN 'Indonésia'
        WHEN 'New Zealand'         THEN 'Nova Zelândia'
        WHEN 'Kenya'               THEN 'Quênia'
        WHEN 'Uruguay'             THEN 'Uruguai'
        WHEN 'South Korea'         THEN 'Coreia do Sul'
        WHEN 'Switzerland'         THEN 'Suíça'
        WHEN 'Czech Republic'      THEN 'República Tcheca'
        WHEN 'Czechia'             THEN 'República Tcheca'
        WHEN 'Venezuela'           THEN 'Venezuela'
        WHEN 'Tanzania'            THEN 'Tanzânia'
        WHEN 'Morocco'             THEN 'Marrocos'
        WHEN 'Poland'              THEN 'Polônia'
        WHEN 'Ukraine'             THEN 'Ucrânia'
        WHEN 'Turkey'              THEN 'Turquia'
        WHEN 'Italy'               THEN 'Itália'
        WHEN 'Denmark'             THEN 'Dinamarca'
        WHEN 'Bolivia'             THEN 'Bolívia'
        WHEN 'Trinidad and Tobago' THEN 'Trinidad e Tobago'
        WHEN 'Philippines'         THEN 'Filipinas'
        WHEN 'Qatar'               THEN 'Catar'
        WHEN 'Egypt'               THEN 'Egito'
        WHEN 'Greece'              THEN 'Grécia'
        WHEN 'Guatemala'           THEN 'Guatemala'
        WHEN 'China PR'            THEN 'China'
        WHEN 'Romania'             THEN 'Romênia'
        WHEN 'Hungary'             THEN 'Hungria'
        WHEN 'DR Congo'            THEN 'Congo'
        WHEN 'Thailand'            THEN 'Tailândia'
        WHEN 'Sweden'              THEN 'Suécia'
        WHEN 'Scotland'            THEN 'Escócia'
        WHEN 'Albania'             THEN 'Albânia'
        WHEN 'Bahrain'             THEN 'Bahrein'
        ELSE name
    END,
    short_name = CASE short_name
        WHEN 'Mexico'              THEN 'México'
        WHEN 'United States'       THEN 'EUA'
        WHEN 'Canada'              THEN 'Canadá'
        WHEN 'Serbia'              THEN 'Sérvia'
        WHEN 'Panama'              THEN 'Panamá'
        WHEN 'Algeria'             THEN 'Argélia'
        WHEN 'Ecuador'             THEN 'Equador'
        WHEN 'Ivory Coast'         THEN 'C. do Marfim'
        WHEN 'Germany'             THEN 'Alemanha'
        WHEN 'Japan'               THEN 'Japão'
        WHEN 'Nigeria'             THEN 'Nigéria'
        WHEN 'Colombia'            THEN 'Colômbia'
        WHEN 'Paraguay'            THEN 'Paraguai'
        WHEN 'France'              THEN 'França'
        WHEN 'England'             THEN 'Inglaterra'
        WHEN 'Austria'             THEN 'Áustria'
        WHEN 'Cameroon'            THEN 'Camarões'
        WHEN 'Saudi Arabia'        THEN 'Ar. Saudita'
        WHEN 'Spain'               THEN 'Espanha'
        WHEN 'Netherlands'         THEN 'Holanda'
        WHEN 'Australia'           THEN 'Austrália'
        WHEN 'South Africa'        THEN 'África do Sul'
        WHEN 'Slovenia'            THEN 'Eslovênia'
        WHEN 'Belgium'             THEN 'Bélgica'
        WHEN 'Croatia'             THEN 'Croácia'
        WHEN 'Uruguay'             THEN 'Uruguai'
        WHEN 'South Korea'         THEN 'Coreia do Sul'
        WHEN 'Switzerland'         THEN 'Suíça'
        WHEN 'Czech Republic'      THEN 'Rep. Tcheca'
        WHEN 'Czechia'             THEN 'Rep. Tcheca'
        WHEN 'Morocco'             THEN 'Marrocos'
        WHEN 'Poland'              THEN 'Polônia'
        WHEN 'Ukraine'             THEN 'Ucrânia'
        WHEN 'Turkey'              THEN 'Turquia'
        WHEN 'Italy'               THEN 'Itália'
        WHEN 'Denmark'             THEN 'Dinamarca'
        WHEN 'Bolivia'             THEN 'Bolívia'
        WHEN 'Qatar'               THEN 'Catar'
        WHEN 'Egypt'               THEN 'Egito'
        WHEN 'Greece'              THEN 'Grécia'
        WHEN 'Romania'             THEN 'Romênia'
        WHEN 'Hungary'             THEN 'Hungria'
        WHEN 'Sweden'              THEN 'Suécia'
        WHEN 'Scotland'            THEN 'Escócia'
        WHEN 'Albania'             THEN 'Albânia'
        ELSE short_name
    END;

-- Atualiza também os nomes nas tabelas matches
UPDATE matches SET
    home_team_name = t.name
FROM teams t
WHERE matches.home_team_id = t.external_id;

UPDATE matches SET
    away_team_name = t.name
FROM teams t
WHERE matches.away_team_id = t.external_id;

-- Confirma
SELECT name, short_name, tla FROM teams ORDER BY name LIMIT 20;

-- Atualiza TLAs para padrão brasileiro
UPDATE teams SET tla = CASE tla
    WHEN 'ENG' THEN 'ING'
    WHEN 'GER' THEN 'ALE'
    WHEN 'NED' THEN 'HOL'
    WHEN 'USA' THEN 'EUA'
    WHEN 'KOR' THEN 'COR'
    WHEN 'DEN' THEN 'DIN'
    WHEN 'FRA' THEN 'FRA'
    WHEN 'ESP' THEN 'ESP'
    WHEN 'ITA' THEN 'ITA'
    WHEN 'POR' THEN 'POR'
    WHEN 'BEL' THEN 'BEL'
    WHEN 'CRO' THEN 'CRO'
    WHEN 'SRB' THEN 'SER'
    WHEN 'SUI' THEN 'SUI'
    WHEN 'POL' THEN 'POL'
    WHEN 'UKR' THEN 'UCR'
    WHEN 'TUR' THEN 'TUR'
    WHEN 'GRE' THEN 'GRE'
    WHEN 'ROU' THEN 'ROM'
    WHEN 'HUN' THEN 'HUN'
    WHEN 'SCO' THEN 'ESC'
    WHEN 'ALB' THEN 'ALB'
    WHEN 'SLO' THEN 'ESL'
    WHEN 'CZE' THEN 'RTC'
    WHEN 'AUT' THEN 'AUS'
    WHEN 'SWE' THEN 'SUE'
    WHEN 'AUS' THEN 'AUS'
    WHEN 'NZL' THEN 'NZL'
    WHEN 'JPN' THEN 'JAP'
    WHEN 'KSA' THEN 'ARS'
    WHEN 'IRN' THEN 'IRA'
    WHEN 'PHI' THEN 'FIL'
    WHEN 'THA' THEN 'TAI'
    WHEN 'IDN' THEN 'INO'
    WHEN 'CHN' THEN 'CHI'
    WHEN 'QAT' THEN 'CAT'
    WHEN 'EGY' THEN 'EGI'
    WHEN 'MAR' THEN 'MAR'
    WHEN 'ALG' THEN 'ARG'
    WHEN 'NGA' THEN 'NIG'
    WHEN 'CMR' THEN 'CAM'
    WHEN 'SEN' THEN 'SEN'
    WHEN 'CIV' THEN 'CDM'
    WHEN 'GHA' THEN 'GAN'
    WHEN 'RSA' THEN 'AFS'
    WHEN 'TAN' THEN 'TAN'
    WHEN 'KEN' THEN 'QUE'
    WHEN 'ANG' THEN 'ANG'
    WHEN 'CGO' THEN 'CON'
    WHEN 'TOG' THEN 'TOG'
    WHEN 'MEX' THEN 'MEX'
    WHEN 'CAN' THEN 'CAN'
    WHEN 'COL' THEN 'COL'
    WHEN 'ARG' THEN 'ARG'
    WHEN 'BRA' THEN 'BRA'
    WHEN 'URU' THEN 'URU'
    WHEN 'CHI' THEN 'CHI'
    WHEN 'PER' THEN 'PER'
    WHEN 'ECU' THEN 'EQU'
    WHEN 'PAR' THEN 'PAR'
    WHEN 'BOL' THEN 'BOL'
    WHEN 'VEN' THEN 'VEN'
    WHEN 'CRC' THEN 'CRC'
    WHEN 'PAN' THEN 'PAN'
    WHEN 'HON' THEN 'HON'
    WHEN 'JAM' THEN 'JAM'
    WHEN 'TRI' THEN 'TTO'
    WHEN 'CUB' THEN 'CUB'
    WHEN 'GTM' THEN 'GUA'
    WHEN 'HTI' THEN 'HAI'
    WHEN 'BHR' THEN 'BAR'
    ELSE tla
END;

-- Confirma TLAs
SELECT name, tla FROM teams ORDER BY name;
